// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180624123815_Nullables")]
    partial class Nullables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FlConfirmation");

                    b.Property<int>("InstalmentQuantity");

                    b.Property<DateTime>("PassThroughDate");

                    b.Property<decimal>("PassThroughValue");

                    b.Property<int?>("TransactionAnticipationID");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<decimal>("TransactionValue");

                    b.HasKey("TransactionID");

                    b.HasIndex("TransactionAnticipationID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.TransactionAnticipation", b =>
                {
                    b.Property<int>("TransactionAnticipationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AnalysisDate");

                    b.Property<bool?>("AnticipationResult");

                    b.Property<DateTime>("SolicitationDate");

                    b.Property<int>("Status");

                    b.Property<decimal>("TotalPassThroughValue");

                    b.Property<decimal>("TotalTransactionValue");

                    b.HasKey("TransactionAnticipationID");

                    b.ToTable("TransactionAnticipations");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.TransactionAnticipation", "TransactionAnticipation")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionAnticipationID");
                });
#pragma warning restore 612, 618
        }
    }
}
